import os
import json
import re
import google.generativeai as genai
from datetime import datetime, timezone
from dotenv import load_dotenv
from supabase import create_client, Client
from google.api_core.exceptions import ResourceExhausted, ServiceUnavailable, InternalServerError

# Load environment variables
load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_PUBLISHABLE_DEFAULT_KEY")

# Models
PRIMARY_MODEL_NAME = "gemini-2.5-flash"
FALLBACK_MODEL_NAME = "gemini-2.5-flash-lite"

if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

DEFAULT_SYSTEM_PROMPT = """**Role:**
You are an expert Visa Consultant for the Destination Thailand Visa (DTV). Your goal is to assist clients in applying for the DTV, qualifying their eligibility, troubleshooting issues, and guiding them to use the agency's mobile app for document submission.

**Tone & Style:**
  * **Professional yet Friendly:** Use polite language, but remain efficient.
  * **Empathetic:** Acknowledge frustrations (especially regarding rejections or payment issues).
  * **Emoji Use:** Use emojis sparingly but effectively to maintain a warm tone (e.g., 🇹🇭, 🎉, 📱, 💪).
  * **Clear Formatting:** Use numbered lists for requirements or steps to ensure readability.

**Directives:**
  * **Remote Workers:** Must work for companies *outside* Thailand.
  * **Pricing:** Standard 18,000 THB.
  * **Workflow:** Consult -> App Download -> Review -> Payment -> Submission.
"""


EDITOR_PROMPT = """You are a Senior AI Prompt Engineer and Optimization System. Your goal is to surgically refine a "System Prompt" to make an AI Chatbot behave exactly like a top-performing human consultant.

### INPUTS
1. **Current System Prompt:** The instructions currently governing the AI.
2. **Conversation Context:** The client's message and chat history.
3. **AI Reply (Flawed):** The suboptimal response generated by the AI.
4. **Human Consultant Reply (Ideal):** The ground-truth response from an expert.

### YOUR PROCESS
1. **Analyze the Gap:** Compare the AI Reply vs. Human Reply. Identify the *root cause* of the failure.
   - *Knowledge Gap:* Did the human know a fact (price, rule) that the AI didn't?
   - *Tone Mismatch:* Was the human more empathetic, concise, or sales-oriented?
   - *Logic Failure:* Did the AI fail to ask a required qualifying question?
2. **Locate the Section:** Decide where the fix belongs (e.g., "Tone & Style", "Knowledge Base", or "Directives").
3. **Draft the Fix:** Create a specific, standalone rule or fact to bridge the gap.
4. **Integrate:** Insert this new rule into the Current System Prompt without breaking the existing structure.

### STRICT EDITING RULES (CRITICAL)
- **Do NOT Delete:** Never remove existing rules unless they directly contradict the Human Reply.
- **Do NOT Overfit:** If the human mentions a specific client name, do not add that name to the prompt. Extract the *general principle* (e.g., "If client is in Bali..." -> "Remote workers in SE Asia...").
- **Maintain Structure:** You MUST preserve the existing Markdown headers, bullet points, and numbering format.
- **Priority:** The Human Reply is the source of truth. If it contradicts the Current Prompt, overwrite the Current Prompt.

### OUTPUT FORMAT
Return a **single JSON object** (no markdown formatting outside the JSON string):
{
  "prompt": "THE_FULL_UPDATED_SYSTEM_PROMPT",
  "change_log": "concise_summary_of_changes"
}
"""

MANUAL_EDITOR_PROMPT = """You are a Senior AI Prompt Architect. Your goal is to manually update the "System Instructions" for a customer support chatbot based on explicit administrative directives.

### INPUTS
1. **Current System Prompt:** The instructions currently governing the AI.
2. **User Instructions:** A specific command to change behavior (e.g., "Stop using emojis," "Add a rule that we don't accept crypto," "Be more aggressive").

### YOUR PROCESS
1. **Analyze the Request:** Determine if the user wants to change **Tone**, **Knowledge**, or **Workflow**.
2. **Locate the Section:** Find the relevant header in the Current System Prompt (e.g., `**Tone & Style**` or `**Knowledge Base**`).
3. **Surgical Insertion:**
   - If changing tone, modify the adjectives or style guidelines in the Tone section.
   - If adding a fact, append a new bullet point in the Knowledge section.
   - If overriding a rule, replace the old rule with the new one.
4. **Preserve Structure:** Do NOT change the Markdown headers or the general format of the prompt. Only modify the content necessary to fulfill the request.

### SAFEGUARD
- If the User Instruction contradicts a fundamental fact (e.g., "Say the visa is free"), YOU MUST COMPLY (you are following admin orders), but try to integrate it smoothly.
- Do not delete unrelated sections.

### OUTPUT FORMAT
Return a **single JSON object** (no markdown formatting outside the JSON string):
{
  "prompt": "THE_FULL_UPDATED_SYSTEM_PROMPT",
  "change_log": "Brief confirmation of what was changed (e.g., 'Removed emoji usage guidelines as requested')."
}
"""

# Global variable to cache the prompt (optional, but good for performance)
CACHED_SYSTEM_PROMPT = None

def get_system_prompt():
    global CACHED_SYSTEM_PROMPT
    if CACHED_SYSTEM_PROMPT:
        return CACHED_SYSTEM_PROMPT

    if not SUPABASE_URL or not SUPABASE_KEY:
        print("Warning: SUPABASE_URL or SUPABASE_KEY missing. Using fallback.")
        return DEFAULT_SYSTEM_PROMPT

    try:
        supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
        # Fetch the single active row
        response = supabase.table("system_prompt") \
            .select("prompt") \
            .eq("is_active", True) \
            .limit(1) \
            .execute()
        
        if response.data and len(response.data) > 0:
            row = response.data[0]
            prompt = row.get("prompt")
            if prompt:
                CACHED_SYSTEM_PROMPT = prompt
                return prompt
    except Exception as e:
        print(f"Error fetching from Supabase: {e}")
    
    return DEFAULT_SYSTEM_PROMPT

def get_max_version(supabase: Client) -> int:
    try:
        # We need to find the max version. 
        # Supabase select order desc + limit 1 is efficient.
        response = supabase.table("system_prompt") \
            .select("version") \
            .order("version", desc=True) \
            .limit(1) \
            .execute()
        
        if response.data and len(response.data) > 0:
            return response.data[0].get("version", 0)
        return 0
    except Exception as e:
        print(f"Error fetching max version: {e}")
        return 0

def save_new_prompt_version(new_text: str, reason: str) -> bool:
    """
    Inserts a new prompt version and sets it as active.
    Deactivates all other rows first.
    Sets 'parent_version' to the currently active version to support tree-based rollback.
    """
    global CACHED_SYSTEM_PROMPT
    
    if not SUPABASE_URL or not SUPABASE_KEY:
        print("Warning: Cannot update Supabase (missing credentials).")
        return False
        
    try:
        supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
        
        # 1. Get current max version
        current_max = get_max_version(supabase)
        new_version = current_max + 1
        
        # 2. Identify the PARENT version (the currently active one)
        parent_version = None
        active_resp = supabase.table("system_prompt").select("version").eq("is_active", True).limit(1).execute()
        if active_resp.data and len(active_resp.data) > 0:
            parent_version = active_resp.data[0].get("version")
        
        now = datetime.now(timezone.utc).isoformat()
        
        # 3. Deactivate all rows (Batch update)
        supabase.table("system_prompt").update({"is_active": False}).eq("is_active", True).execute()
        
        # 4. Insert new active row with parent_version
        insert_data = {
            "prompt": new_text,
            "version": new_version,
            "is_active": True,
            "change_log": reason,
            "created_at": now,
            "parent_version": parent_version
        }
        
        insert_resp = supabase.table("system_prompt").insert(insert_data).execute()
        
        if insert_resp.data:
            print(f"Successfully saved new prompt version {new_version} (Parent: {parent_version}).")
            CACHED_SYSTEM_PROMPT = new_text
            return True
        else:
            print("Warning: Supabase insert returned no data.")
            return False
            
    except Exception as e:
        print(f"Error saving new prompt version: {e}")
        return False

def rollback_prompt(steps: int = 1) -> bool:
    """
    Rolls back the active prompt.
    If 'parent_version' exists, it traverses back up the tree.
    Otherwise, it falls back to linear decrement/steps mechanism if steps > 1 or no parent info.
    """
    global CACHED_SYSTEM_PROMPT
    
    if not SUPABASE_URL or not SUPABASE_KEY:
        return False
        
    try:
        supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
        
        # 1. Find currently active version
        # We need the 'parent_version' column now
        active_resp = supabase.table("system_prompt").select("version", "parent_version").eq("is_active", True).single().execute()
        if not active_resp.data:
            print("No active prompt found to rollback from.")
            return False
            
        current_version_num = active_resp.data.get("version")
        parent_version_num = active_resp.data.get("parent_version")
        
        target_version = None
        
        # LOGIC:
        # If we just want to go back 1 step AND we have a parent_version, follow the tree.
        if steps == 1 and parent_version_num is not None:
            target_version = parent_version_num
            print(f"Tree-based rollback: {current_version_num} -> {target_version}")
        else:
            # Fallback for >1 steps or missing parent data (legacy rows)
            # This logic is approximate for >1 steps in a tree, traversing multiple parents would be better but complex.
            # For this MVP, if steps > 1, we just subtract.
            print(f"Linear/Legacy rollback: {current_version_num} - {steps}")
            target_version = current_version_num - steps
        
        if target_version < 1:
            print(f"Cannot rollback to version {target_version}. Minimum version is 1.")
            return False
            
        # 2. Verify target exists and fetch prompt
        target_resp = supabase.table("system_prompt").select("prompt").eq("version", target_version).single().execute()
        if not target_resp.data:
            print(f"Target version {target_version} does not exist.")
            return False
            
        target_prompt = target_resp.data.get("prompt")
        
        # 3. Perform Switch
        supabase.table("system_prompt").update({"is_active": False}).eq("is_active", True).execute()
        supabase.table("system_prompt").update({"is_active": True}).eq("version", target_version).execute()
        
        print(f"Successfully rolled back to version {target_version}.")
        CACHED_SYSTEM_PROMPT = target_prompt
        return True
        
    except Exception as e:
        print(f"Error rolling back prompt: {e}")
        return False

import re

# ... (existing imports, but keep the ones below)

def extract_json(text_response):
    """
    Helper to robustly extract JSON from a response string.
    """
    try:
        # First try simple JSON load
        return json.loads(text_response)
    except json.JSONDecodeError:
        pass

    # Clean up markdown code blocks if present
    cleaned_text = text_response
    if "```json" in cleaned_text:
        cleaned_text = cleaned_text.split("```json")[1].split("```")[0].strip()
    elif "```" in cleaned_text:
        cleaned_text = cleaned_text.split("```")[1].split("```")[0].strip()

    try:
        return json.loads(cleaned_text)
    except json.JSONDecodeError:
        pass

    # Try regex to find the first { and last }
    try:
        match = re.search(r'\{.*\}', text_response, re.DOTALL)
        if match:
            json_str = match.group(0)
            return json.loads(json_str)
    except json.JSONDecodeError:
        pass
        
    # If all else fails, return None or raw text wrapper
    return None

def generate_with_fallback(full_prompt):
    """
    Attempts to generate content with the primary model.
    If it fails due to rate limits or errors, falls back to the lite model.
    """
    try:
        model = genai.GenerativeModel(PRIMARY_MODEL_NAME)
        return model.generate_content(full_prompt)
    except (ResourceExhausted, ServiceUnavailable, InternalServerError) as e:
        print(f"Primary model {PRIMARY_MODEL_NAME} failed: {e}. Falling back to {FALLBACK_MODEL_NAME}.")
        try:
            model = genai.GenerativeModel(FALLBACK_MODEL_NAME)
            return model.generate_content(full_prompt)
        except Exception as e2:
            print(f"Fallback model {FALLBACK_MODEL_NAME} also failed: {e2}")
            # Reraise or return None? Let's return the exception or re-raise
            raise e2
    except Exception as e:
        print(f"Unexpected error with {PRIMARY_MODEL_NAME}: {e}")
        raise e

def generate_reply(client_message, chat_history):
    """
    Generates a reply using the Gemini API.
    
    Args:
        client_message (str): The latest message from the client.
        chat_history (list): List of dicts checks [{"role": "user"|"assistant", "content": "..."}]
    """
    if not GEMINI_API_KEY:
        return "Error: API Key missing"

    system_prompt = get_system_prompt()
    
    prompt_input = {
        "chat_history": chat_history,
        "incoming_messages": [client_message]
    }
    
    full_prompt = f"{system_prompt}\n\nInput:\n{json.dumps(prompt_input, indent=2)}"
    
    try:
        response = generate_with_fallback(full_prompt)
        text_response = response.text
        
        result = extract_json(text_response)
        if result and isinstance(result, dict):
            return result.get("reply", text_response)
        else:
             return text_response

    except Exception as e:
        return f"Error generating reply: {e}"

def optimize_prompt(client_seq_text, chat_history, ai_reply, consultant_reply):
    """
    Optimizes the system prompt based on comparison between AI and Consultant.
    """
    if not GEMINI_API_KEY:
        return None

    current_prompt = get_system_prompt()

    context_str = json.dumps({
        "client_messages": [client_seq_text],
        "chat_history": chat_history
    }, indent=2)

    optimization_input = f"""
1. **Current System Prompt:**
{current_prompt}

2. **Conversation Context:**
{context_str}

3. **AI Reply (Flawed):**
{ai_reply}

4. **Human Consultant Reply (Ideal):**
{consultant_reply}
"""

    full_editor_prompt = f"{EDITOR_PROMPT}\n\n{optimization_input}"

    try:
        response = generate_with_fallback(full_editor_prompt)
        text_resp = response.text
        
        result = extract_json(text_resp)
        if not result:
             # Fallback or log error
             return current_prompt

        new_prompt = result.get("prompt")
        reason = result.get("change_log", "Automated optimization")
        
        if new_prompt and new_prompt != current_prompt:
            save_new_prompt_version(new_text=new_prompt, reason=reason)
            return {"prompt": new_prompt, "change_log": reason}
        
        return {"prompt": current_prompt, "change_log": "No changes made."}

    except Exception as e:
        print(f"Error during prompt optimization: {e}")
        return {"prompt": current_prompt, "change_log": f"Error: {str(e)}"}

def update_system_prompt_with_instructions(instructions):
    """
    Manually updates the prompt based on instructions.
    """
    if not GEMINI_API_KEY:
        return None

    current_prompt = get_system_prompt()
    
    input_text = f"""
1. **Current System Prompt:**
{current_prompt}

2. **User Instructions:**
{instructions}
"""
    
    full_prompt = f"{MANUAL_EDITOR_PROMPT}\n\n{input_text}"
    
    try:
        response = generate_with_fallback(full_prompt)
        text_resp = response.text
        
        result = extract_json(text_resp)
        if not result:
             print(f"Failed to parse JSON from AI response: {text_resp[:100]}...")
             return current_prompt
             
        new_prompt = result.get("prompt")
        reason = result.get("change_log", f"Manual update: {instructions}")
        
        if new_prompt and new_prompt != current_prompt:
            save_new_prompt_version(new_text=new_prompt, reason=reason)
            return {"prompt": new_prompt, "change_log": reason}
        
        return {"prompt": current_prompt, "change_log": "No changes made."}
        
    except Exception as e:
        print(f"Error manual prompt update: {e}")
        return {"prompt": current_prompt, "change_log": f"Error: {str(e)}"}
